services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ken123
      POSTGRES_DB: blog
networks:
  postgres-network:
    driver: bridge
